version: '3'

services:
  cs:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: "cs:latest"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - pg
    volumes:
      - "../:/app"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_URI
  pg:
    image: "postgres"
    volumes:
      - "cs_pg_data:/var/lib/postgresql/data"
      - "./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql"
    environment:
      - POSTGRES_PASSWORD

volumes:
  cs_pg_data:
