name: test
on: [push]
jobs:
  perl:
    runs-on: ubuntu-latest
    container:
      image: perl
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - name: install psql
        run: apt-get update && apt-get install -y --no-install-recommends postgresql-client
      - name: create db
        env:
          PGPASSWORD: postgres
        run: psql -h postgres -U postgres -c 'create database cs_test;'
      - name: install dependencies
        run: cpanm -n --installdeps .
      - name: perl version
        run: perl -v
      - name: postgresq version
        env:
          PGPASSWORD: postgres
        run: psql -h postgres -U postgres -c 'select version();'
      - name: run tests
        env:
          TEST_ONLINE: postgresql://postgres:postgres@postgres:5432/cs_test
        run: prove -lv t
